import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

const genres = [
    'Smooth Jazz',
    'Classic Rock',
    'Easy Listening',
    'Crhistmas',
    'Blues',
    'Jazz',
    'Country',
    'Classical',
    '80s',
    'Rock',
    'Oldies',
    'Dance',
    'House',
    'Lounge',
    'Ambient',
    'Chillout',
    'Top 40',
    'Trance',
    '70s',
    'Techno',
    'Greek',
    'Pop',
    'Reggae',
    'Metal',
    'Psytrance',
    'Deep House',
    'Funk',
    'Instrumental',
    '90s',
    'Hip Hop',
    'Drum And Bass',
    '60s',
    'Disco',
    'Soul',
    'Heavy Metal',
    'Salsa',
    'Bollywood',
    '50s',
    'Meditation',
    'Rockabilly',
    'Edm',
    'Hindi',
    'Swing',
    'Chill',
    'Christian',
    'Rap',
    'Talk',
    'Dub',
    'New Age',
    'Big Band',
    'Psychedelic',
    'Tejano',
    'Bluegrass',
    'Latin',
    'Electronic',
    'Downtempo',
    'Comedy',
    'Piano',
    'Celtic',
    'Alternative',
    'Dancehall',
    'Progressive',
    'Jpop',
    'Punk',
    'Anime',
    'Rnb',
    'Hardcore',
    'Relaxation',
    'Tech House',
    'Japanese',
    'Indie',
    'Eurodance',
    'Kpop',
    'Soundtracks',
    'Raggaeton',
    'Polka',
    'Goth',
    'Freestyle',
    'Americana',
    'Dubstep',
]
ReactDOM.render(<App genres={genres}/>, document.querySelector('#root'));